CloudCord/Controllers/ENController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CloudCord.Models;
using PagedList;


namespace CloudCord.Controllers
{
    public class ENController : Controller
    {
        private CloudCord_DB db = new CloudCord_DB();

        //
        // GET: /EN/

        public ActionResult Index(string searchTag = null, DateTime? date1 = null, DateTime? date2 = null, int page = 1)
        {
            IEnumerable<string> fParam = new string[] { "Select filter parametar:", "Tag", "Date" };
            ViewData["myList"] = new SelectList(fParam.Select(x => new { text = x }), null, "text", "Select filter parametar:");

            if (searchTag == null) searchTag = "";

            if (searchTag.Length > 0)
            {
                var model = db.ENcalculation
                            .OrderByDescending(r => r.tagIz)
                            .Where(r => r.tagIz == searchTag)
                            .Select(r => new ENListViewModel
                                     {
                                         izracunId = r.izracunId,
                                         tagIz = r.tagIz,
                                         Eistok = r.Eistok,
                                         Nsjever = r.Nsjever,
                                         xp = r.xp,
                                         yp = r.yp,
                                         createdIz = r.createdIz
                                     }).ToPagedList(page, 10);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ENCalculations", model);
                }

                return View(model);
            }
            else if (date1 != null || date2 != null)
            {
                if (date1 == null) date1 = DateTime.Parse("1/1/0001");
                if (date2 == null) date2 = DateTime.Parse("1/1/9999");
                var model = db.ENcalculation
                            .OrderByDescending(r => r.tagIz)
                            .Where(r => r.createdIz >= date1 && r.createdIz < date2)
                            .Select(r => new ENListViewModel
                            {
                                izracunId = r.izracunId,
                                tagIz = r.tagIz,
                                Eistok = r.Eistok,
                                Nsjever = r.Nsjever,
                                xp = r.xp,
                                yp = r.yp,
                                createdIz = r.createdIz
                            }).ToPagedList(page, 10);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ENCalculations", model);
                }

                return View(model);

            }
            else
            {
                var model = db.ENcalculation
                            .OrderByDescending(r => r.tagIz)
                            .Select(r => new ENListViewModel
                            {
                                izracunId = r.izracunId,
                                tagIz = r.tagIz,
                                Eistok = r.Eistok,
                                Nsjever = r.Nsjever,
                                xp = r.xp,
                                yp = r.yp,
                                createdIz = r.createdIz
                            }).ToPagedList(page, 10);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ENCalculations", model);
                }

                return View(model);
            }
        }


        //
        // GET: /EN/Create

        public ActionResult Create()
        {
            ENconversion model = new ENconversion();
            model.createdIz = DateTime.Today;
            return View(model);
        }

        //
        // POST: /EN/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOption(string submitButton, ENconversion enconversion)
        {
            switch (submitButton)
            {
                case "Calculate":
                    return (Calculate(enconversion));

                case "Save":
                    return (Save(enconversion));

                default:
                    return View("Create");
            }
        }

        private ActionResult Calculate(ENconversion enconversion)
        {

            if (ModelState.IsValid)
            {
                enconversion.Izracun();
            }
            return View("Create", enconversion);
        }


        private ActionResult Save(ENconversion enconversion)
        {
            if (ModelState.IsValid)
            {
                enconversion.Izracun();
                db.ENcalculation.Add(enconversion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Create", enconversion);
        }

        //
        // GET: /EN/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ENconversion enconversion = db.ENcalculation.Find(id);
            if (enconversion == null)
            {
                return HttpNotFound();
            }
            else
            {
                db.ENcalculation.Remove(enconversion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

CloudCord/Controllers/XYController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CloudCord.Models;
using PagedList;

namespace CloudCord.Controllers
{
    [Authorize]
    public class XYController : Controller
    {

        private CloudCord_DB db = new CloudCord_DB();


        //
        // GET: /XY/

        public ActionResult Index(string searchTag = null, DateTime? date1 = null, DateTime? date2 = null, int page = 1)
        {
            IEnumerable<string> fParam = new string[] { "Select filter parametar:", "Tag", "Date" };
            ViewData["myList"] = new SelectList(fParam.Select(x => new { text = x }), null, "text", "Select filter parametar:");

            if (searchTag == null) searchTag = "";

            if (searchTag.Length > 0)
            {
                var model = db.XYcalculation
                            .OrderByDescending(r => r.tagIz)
                            .Where(r => r.tagIz == searchTag)
                            .Select(r => new XYListViewModel
                            {
                                izracunId = r.izracunId,
                                tagIz = r.tagIz,
                                xCoord = r.xCoord,
                                yCoord = r.yCoord,
                                ECoord = r.ECoord,
                                NCoord = r.NCoord,
                                createdIz = r.createdIz
                            }).ToPagedList(page, 10);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_Calculations", model);
                }

                return View(model);
            }
            else if (date1 != null || date2 != null)
            {
                if (date1 == null) date1 = DateTime.Parse("1/1/0001");
                if (date2 == null) date2 = DateTime.Parse("1/1/9999");
                var model = db.XYcalculation
                            .OrderByDescending(r => r.tagIz)
                            .Where(r => r.createdIz >= date1 && r.createdIz < date2)
                            .Select(r => new XYListViewModel
                            {
                                izracunId = r.izracunId,
                                tagIz = r.tagIz,
                                xCoord = r.xCoord,
                                yCoord = r.yCoord,
                                ECoord = r.ECoord,
                                NCoord = r.NCoord,
                                createdIz = r.createdIz
                            }).ToPagedList(page, 10);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_Calculations", model);
                }

                return View(model);
            }
            else
            {
                var model = db.XYcalculation
                            .OrderByDescending(r => r.createdIz)
                            .Select(r => new XYListViewModel
                            {
                                izracunId = r.izracunId,
                                tagIz = r.tagIz,
                                xCoord = r.xCoord,
                                yCoord = r.yCoord,
                                ECoord = r.ECoord,
                                NCoord = r.NCoord,
                                createdIz = r.createdIz
                            }).ToPagedList(page, 10);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_Calculations", model);
                }

                return View(model);

            }



        }



        //
        // GET: /XY/Create

        public ActionResult Create()
        {
            XYconversion model = new XYconversion();
            model.createdIz = DateTime.Today;
            return View(model);
        }

        //
        // POST: /XY/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOption(string submitButton, XYconversion xyconversion)
        {
            switch (submitButton)
            {
                case "Calculate":
                    return (Calculate(xyconversion));

                case "Save":
                    return (Save(xyconversion));

                default:
                    return View("Create");
            }
        }

        private ActionResult Calculate(XYconversion xyconversion)
        {

            if (ModelState.IsValid)
            {
                xyconversion.izracun();
            }
            return View("Create", xyconversion);
        }


        private ActionResult Save(XYconversion xyconversion)
        {
            if (ModelState.IsValid)
            {
                xyconversion.izracun();
                db.XYcalculation.Add(xyconversion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Create", xyconversion);
        }


        //
        // GET: /XY/Delete/5

        public ActionResult Delete(int id = 0)
        {
            XYconversion xyconversion = db.XYcalculation.Find(id);
            if (xyconversion == null)
            {
                return HttpNotFound();
            }
            else
            {
                db.XYcalculation.Remove(xyconversion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

    }
}

CloudCord/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - CloudCord - convert your coordinates</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/cc")
        @Styles.Render("~/Content/themes/base/css")
        @Ajax.GlobalizationScript()
        
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("CloudCord", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            @if (Request.IsAuthenticated) {
                             <li>@Html.ActionLink("Calculate", "Intro", "Calculate")</li>
                            }

                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @RenderSection("scripts", required: false)
    </body>
</html>

CloudCord/Views/Shared/_MasterCalculate.cshtml
<div class="col2">
    <ul>
        <li>@Html.ActionLink("Introduction", "Intro","Calculate")</li>
        <li>@Html.ActionLink("E-N Conversion", "Index","EN")</li>
        <li>@Html.ActionLink("X-Y Conversion", "Index","XY")</li>
    </ul>
</div>

CloudCord/Views/Shared/_dateForm.cshtml
@using(Html.BeginForm(null, null, FormMethod.Get))
{
    <fieldset>
        <legend>Search by Date:</legend>
        @Html.Label("From:")
        @Html.TextBox("date1", null, new {@class="datepicker" })
        @Html.Label("To:")
        @Html.TextBox("date2", null, new {@class="datepicker" })
     <p>
        <input type="submit" value="Search by date" />
     </p>
    </fieldset>
}
